In [1]:
from pathlib import Path

PROJECT_ROOT = Path("..").resolve()
RAW_FOLDER = PROJECT_ROOT / "data" / "raw"
INTERIM_FOLDER = PROJECT_ROOT / "data" / "interim"

print("Project folder:", PROJECT_ROOT)
print("Raw folder exists:", RAW_FOLDER.exists())
print("Interim folder exists:", INTERIM_FOLDER.exists())

Project folder: C:\Users\disha\ecommerce-delivery-logistics-analysis
Raw folder exists: True
Interim folder exists: True

In [2]:
csv_files = sorted(RAW_FOLDER.glob("*.csv"))

print("Total CSV files:", len(csv_files))

for file in csv_files:
    print(file.name)

Total CSV files: 9
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/olist_orders_dataset.csv")

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
df.shape

(99441, 8)

In [5]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [6]:
df["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [7]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [8]:
df.groupby("order_status")["order_delivered_customer_date"].apply(
    lambda x: x.isnull().sum()
)

order_status
approved          2
canceled        619
created           5
delivered         8
invoiced        314
processing      301
shipped        1107
unavailable     609
Name: order_delivered_customer_date, dtype: int64

In [9]:
df[
    (df["order_status"] == "delivered") &
    (df["order_delivered_customer_date"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [10]:
df.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [11]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

df[date_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [12]:
(df["order_delivered_customer_date"] < df["order_purchase_timestamp"]).sum()

np.int64(0)

In [13]:
(df["order_delivered_carrier_date"] < df["order_purchase_timestamp"]).sum()

np.int64(166)

In [14]:
df[
    df["order_delivered_carrier_date"] <
    df["order_purchase_timestamp"]
][[
    "order_id",
    "order_purchase_timestamp",
    "order_delivered_carrier_date",
    "order_status"
]].head(10)

,order_id,order_purchase_timestamp,order_delivered_carrier_date,order_status
615,b9afddbdcfadc9a87b41a83271c3e888,2018-08-16 13:50:48,2018-08-16 13:27:00,delivered
1111,ad133696906f6a78826daa0911b7daec,2018-06-15 15:41:22,2018-06-15 14:52:00,delivered
1329,74e033208dc13a7b8127eb8e73d09b76,2018-05-02 10:48:44,2018-05-02 09:49:00,delivered
1372,a6b58794fd2ba533359a76c08df576e3,2018-05-14 15:18:23,2018-05-14 13:46:00,delivered
1864,5792e0b1c8c8a2bf53af468c9a422c88,2018-07-26 13:25:14,2018-07-26 12:42:00,delivered
2760,c3eb293fd154223498b6551a728203e8,2018-07-19 14:06:04,2018-07-19 13:49:00,delivered
3473,b0c2a7d04b165525254254a728c50a4e,2018-06-07 13:28:30,2018-06-07 13:22:00,delivered
3661,2033a4586b5bec3229ebc1675a8ae092,2018-06-12 10:10:25,2018-06-12 10:09:00,delivered
4114,08adcddad19d3acf37d1fa01cb9ded1e,2018-06-27 11:16:44,2018-06-27 10:57:00,delivered
4159,dee6298ce7d1fb2645141ef9972157aa,2018-04-30 14:06:12,2018-04-30 12:59:00,shipped

In [15]:
df["carrier_time_difference"] = (
    df["order_delivered_carrier_date"] -
    df["order_purchase_timestamp"]
).dt.total_seconds() / 60

df.loc[
    df["carrier_time_difference"] < 0,
    "carrier_time_difference"
].describe()

count       166.000000
mean      -1562.368675
std       19135.430706
min     -246545.883333
25%         -61.050000
50%         -35.991667
75%         -14.066667
max          -0.400000
Name: carrier_time_difference, dtype: float64

In [16]:
df.nsmallest(5, "carrier_time_difference")[
    [
        "order_id",
        "order_purchase_timestamp",
        "order_delivered_carrier_date",
        "carrier_time_difference"
    ]
]

,order_id,order_purchase_timestamp,order_delivered_carrier_date,carrier_time_difference
25883,7c48bb55e8e4f7e56d412e9653db37bc,2018-07-16 18:40:53,2018-01-26 13:35:00,-246545.883333
83321,4021cd7611d6d9ce5ffcd24817fc374f,2018-08-18 11:49:40,2018-08-14 06:22:00,-6087.666667
67844,db090a16182b263b1e896bb26c6f66cf,2018-07-13 16:14:08,2018-07-13 13:59:00,-135.133333
65452,9711d975b961355b4b5d636857e48498,2018-06-13 15:23:50,2018-06-13 13:15:00,-128.833333
79401,89d32b64af005178b318f76cd60f2c3c,2018-07-06 11:54:40,2018-07-06 09:48:00,-126.666667

In [17]:
(
    df["order_delivered_customer_date"] >
    df["order_estimated_delivery_date"]
).sum()

np.int64(7827)

In [18]:
delivered = df[
    (df["order_status"] == "delivered") &
    (df["order_delivered_customer_date"].notna())
]

late_orders = delivered[
    delivered["order_delivered_customer_date"] >
    delivered["order_estimated_delivery_date"]
]

print("Delivered orders:", len(delivered))
print("Late deliveries:", len(late_orders))
print("Late delivery percentage:", round(len(late_orders) / len(delivered) * 100, 2), "%")

Delivered orders: 96470
Late deliveries: 7826
Late delivery percentage: 8.11 %